# Generated by Django 6.0.8 on 2026-08-16 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionaldocument',
            name='content_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of document for auditability', max_length=128),
        ),
    ]
