# Generated by Django 6.0.8 on 2026-08-16 13:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_institutionstaff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_at_unit', models.CharField(choices=[('DEAN', 'Dean of Division'), ('SUB_DEAN', 'Sub-Dean (Academics / Student Affairs)'), ('HOD', 'Head of Department (HOD)'), ('DEPARTMENTAL_COUNSELLOR', 'Departmental Career Counsellor'), ('FACULTY_COUNSELLOR', 'Faculty Lead Counsellor'), ('SIWES_COORDINATOR', 'Departmental SIWES Coordinator'), ('ACADEMIC_ADVISER', 'Level Academic Adviser'), ('FACULTY_EVALUATOR', 'Technical Milestone Evaluator'), ('DIRECTOR_CAREER_SERVICES', 'Director of Career Services (Institution-Wide)'), ('SUPERADMIN', 'Institution Superadmin')], default='FACULTY_EVALUATOR', max_length=40)),
                ('official_title', models.CharField(blank=True, help_text='e.g. Academic Adviser — 300L SLT Track', max_length=200)),
                ('assigned_years_of_study', models.JSONField(blank=True, default=list, help_text='List of years of study assigned (e.g. [3, 4, 5])')),
                ('can_evaluate_milestones', models.BooleanField(default=True, help_text='Permission to authenticate student evidence and milestones')),
                ('can_manage_waivers', models.BooleanField(default=False, help_text='Permission to grant prerequisite waivers for SIWES placement')),
                ('max_caseload', models.PositiveIntegerField(default=150, help_text='Maximum student caseload allocation')),
                ('is_primary', models.BooleanField(default=True, help_text="Marks this assignment as the staff member's primary institutional post")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, help_text='If set, staff is scoped to this specific department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_assignments', to='institutions.department')),
                ('division', models.ForeignKey(blank=True, help_text='If set and department is null, staff is scoped to the entire division/faculty', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_assignments', to='institutions.academicdivision')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='institutions.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Assignment',
                'verbose_name_plural': 'Staff Assignments',
                'ordering': ['institution', 'department', 'user__name'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matric_number', models.CharField(db_index=True, help_text='e.g. 2021/1/74892CS or GSU/SCI/CSC/22/0104', max_length=50)),
                ('jamb_reg_number', models.CharField(blank=True, db_index=True, help_text='JAMB registration number for national verification', max_length=50)),
                ('entry_mode', models.CharField(choices=[('UTME', 'UTME (Standard Entry - Year 1)'), ('DIRECT_ENTRY', 'Direct Entry (DE - Year 2)'), ('TRANSFER', 'Inter-Faculty / University Transfer'), ('CONVERSION', 'HND to B.Sc. Conversion')], default='UTME', max_length=20)),
                ('year_of_study', models.PositiveSmallIntegerField(default=1, help_text='Current year of study (1 to 6), e.g. 1 for 100L/ND I, 4 for 400L/HND II, 5 for 500L SLT/Eng')),
                ('is_spillover', models.BooleanField(default=False, help_text='True if student has exceeded standard program duration')),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, help_text='Current cumulative grade point average (e.g. 4.35)', max_digits=4, null=True)),
                ('academic_standing', models.CharField(choices=[('IN_GOOD_STANDING', 'In Good Standing'), ('PROBATION', 'Academic Warning / Probation'), ('SIWES_SUSPENDED', 'SIWES Clearance Suspended'), ('GRADUATED', 'Graduated (Awaiting NYSC)'), ('ALUMNI', 'Alumni / Post-NYSC'), ('DEFERRED', 'Session Deferred')], default='IN_GOOD_STANDING', max_length=30)),
                ('siwes_clearance_status', models.CharField(choices=[('NOT_ELIGIBLE', 'Not Yet Eligible (Pre-SIWES Year)'), ('QUALIFYING', 'Qualifying (Prerequisites in Progress)'), ('CLEARED', 'Cleared by HOD & Coordinator (Ready for Placement)'), ('ON_ATTACHMENT', 'Active On Attachment'), ('COMPLETED', 'Attachment Logbook & Presentation Completed')], default='NOT_ELIGIBLE', max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('state_of_origin', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(blank=True, max_length=15)),
                ('bio', models.TextField(blank=True)),
                ('portfolio_url', models.URLField(blank=True, help_text='Link to student GitHub, Behance, or live project repository')),
                ('linkedin_url', models.URLField(blank=True)),
                ('is_verified_student', models.BooleanField(default=True, help_text='True if matched with institutional admissions ledger')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculated_students', to='institutions.academicsession')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='institutions.institution')),
                ('program', models.ForeignKey(help_text='Tier-4 degree option (which links to Department -> Division -> Institution)', on_delete=django.db.models.deletion.PROTECT, related_name='enrolled_students', to='institutions.academicprogram')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'ordering': ['institution', 'program', 'matric_number'],
                'indexes': [models.Index(fields=['institution', 'year_of_study'], name='institution_institu_611577_idx'), models.Index(fields=['program', 'year_of_study'], name='institution_program_af959d_idx')],
                'constraints': [models.UniqueConstraint(fields=('institution', 'matric_number'), name='unique_matric_per_institution')],
            },
        ),
    ]
