# Generated by Django 6.0.8 on 2026-08-16 13:41

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_staffassignment_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionaldocument',
            name='file',
            field=models.FileField(blank=True, help_text='Uploaded handbook or guidelines document (PDF, DOCX, TXT)', null=True, upload_to='institutional_documents/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='institutionaldocument',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Academic session this document applies to (e.g. 2025/2026)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='institutions.academicsession'),
        ),
        migrations.AddField(
            model_name='institutionaldocumentchunk',
            name='is_header',
            field=models.BooleanField(default=False, help_text='Indicates whether this chunk represents a major section heading or table of contents'),
        ),
        migrations.AlterField(
            model_name='institutionaldocumentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, help_text='384-dimensional vector embedding (bge-small-en-v1.5 / all-MiniLM-L6-v2) for cosine similarity search in PostgreSQL', null=True),
        ),
    ]
