# Generated by Django 6.0.8 on 2026-08-16 14:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_institutionaldocument_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='e.g. Full-Stack Web & Cloud Architecture', max_length=200)),
                ('career_role', models.CharField(help_text='Target role e.g. Full-Stack Software Engineer, DevOps Specialist', max_length=150)),
                ('industry_sector', models.CharField(blank=True, help_text='e.g. Information Technology / Fintech / Telecommunications', max_length=100)),
                ('description', models.TextField(help_text='Comprehensive overview of competencies and expected learning outcomes')),
                ('target_cgpa_recommendation', models.DecimalField(blank=True, decimal_places=2, help_text='Recommended minimum CGPA (e.g. 3.00)', max_digits=4, null=True)),
                ('total_milestones_count', models.PositiveIntegerField(default=0)),
                ('total_points', models.PositiveIntegerField(default=0, help_text='Total employability points accumulated across all milestones')),
                ('is_active', models.BooleanField(default=True)),
                ('is_template', models.BooleanField(default=False, help_text='If True, serves as a master template blueprint in the institutional catalog')),
                ('template_visibility', models.CharField(choices=[('DEPARTMENT', 'Department Only'), ('INSTITUTION', 'Institution-Wide'), ('NATIONAL_CATALOG', 'National Open Catalog')], default='INSTITUTION', max_length=25)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cloned_from', models.ForeignKey(blank=True, help_text='Master template from which this pathway was cloned', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloned_derivatives', to='institutions.pathway')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pathways', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathways', to='institutions.institution')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathways', to='institutions.academicprogram')),
            ],
            options={
                'verbose_name': 'Career Pathway',
                'verbose_name_plural': 'Career Pathways',
                'ordering': ['program', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PathwayMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_index', models.PositiveSmallIntegerField(default=0, help_text='Sequence order within the pathway')),
                ('year_of_study', models.PositiveSmallIntegerField(default=1, help_text='Target academic year (1..5) matching student year of study')),
                ('target_level_code', models.CharField(blank=True, help_text="e.g. '100', '200', '300', '400', '500', 'ND_I', 'ND_II', 'NCE_I', 'NCE_II', 'NCE_III'", max_length=20)),
                ('target_semester', models.CharField(choices=[('FIRST', 'First Semester'), ('SECOND', 'Second Semester'), ('BOTH', 'Both Semesters / Annual')], default='FIRST', max_length=20)),
                ('title', models.CharField(help_text='e.g. Deploy Modular Microservice with CI/CD Pipeline', max_length=255)),
                ('description', models.TextField(help_text='Specific deliverables, rubric criteria, and requirements')),
                ('milestone_type', models.CharField(choices=[('FOUNDATIONAL_COURSEWORK', 'Foundational Coursework Prerequisite'), ('TECHNICAL_SKILL', 'Technical Skill Mastery'), ('GITHUB_PROJECT', 'Production Repository / Deployed App'), ('INDUSTRY_CERTIFICATION', 'Industry Recognized Certification'), ('SIWES_PREREQUISITE', 'SIWES / ITCC Placement Clearance'), ('INTERNSHIP_EXPERIENCE', 'Internship / Work Placement'), ('CAPSTONE_PROJECT', 'Final Year Capstone Project Defense'), ('CAREER_READINESS', 'Portfolio & Technical Interview Readiness')], default='TECHNICAL_SKILL', max_length=30)),
                ('points', models.PositiveIntegerField(default=100, help_text='Employability weighting score assigned to this milestone')),
                ('is_mandatory', models.BooleanField(default=True, help_text='Whether completion is strictly required for pathway badge')),
                ('verification_method', models.CharField(choices=[('SUPERVISOR_SIGN_OFF', 'Counsellor / HOD Sign-Off'), ('URL_VERIFICATION', 'Repository / Live URL Review'), ('DOCUMENT_UPLOAD', 'Certificate / Document PDF Upload'), ('AUTOMATED_ASSESSMENT', 'Automated Assessment / Quiz')], default='SUPERVISOR_SIGN_OFF', max_length=30)),
                ('required_evidence_type', models.CharField(choices=[('GITHUB_REPO', 'GitHub / GitLab Repository URL'), ('LIVE_URL', 'Live Deployed Project URL'), ('CERTIFICATE_PDF', 'Certificate PDF / Verified Credential Link'), ('PORTFOLIO_LINK', 'Portfolio Link (Behance, Dribbble, Personal Site)'), ('SUPERVISOR_ENDORSEMENT', 'Faculty / Industry Supervisor Form')], default='GITHUB_REPO', max_length=30)),
                ('competency_tags', models.JSONField(blank=True, default=list, help_text="List of skill keywords, e.g. ['React', 'TypeScript', 'Docker', 'PostgreSQL']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='institutions.pathway')),
            ],
            options={
                'verbose_name': 'Pathway Milestone',
                'verbose_name_plural': 'Pathway Milestones',
                'ordering': ['pathway', 'order_index', 'year_of_study'],
            },
        ),
    ]
