# Generated by Django 6.0.8 on 2026-08-16 14:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0006_pathway_pathwaymilestone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='active_pathway',
            field=models.ForeignKey(blank=True, help_text='The career pathway this student is currently actively pursuing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_students', to='institutions.pathway'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='employability_score',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Composite Employability Score (0.00 - 100.00%) based on verified milestones (70%) and CGPA (30%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='milestones_completed_count',
            field=models.PositiveIntegerField(default=0, help_text='Count of verified milestone submissions'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='verified_points_total',
            field=models.PositiveIntegerField(default=0, help_text='Total verified milestone points accumulated by this student'),
        ),
        migrations.CreateModel(
            name='StudentMilestoneSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('VERIFIED', 'Verified & Points Awarded'), ('CHANGES_REQUESTED', 'Changes / Re-submission Requested'), ('REJECTED', 'Rejected / Incomplete')], default='PENDING_REVIEW', max_length=25)),
                ('evidence_url', models.URLField(blank=True, help_text='GitHub repository URL or Live demo deployment link', null=True)),
                ('evidence_file', models.FileField(blank=True, help_text='Uploaded certificate PDF or supervisor endorsement form', null=True, upload_to='student_evidence/%Y/%m/')),
                ('submission_notes', models.TextField(blank=True, help_text='Student description of work completed, architectural decisions, or SIWES context')),
                ('points_awarded', models.PositiveIntegerField(default=0, help_text='Points awarded upon verification (defaults to milestone.points)')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_feedback', models.TextField(blank=True, help_text='Counsellor or HOD remarks and evaluation notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='institutions.pathwaymilestone')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_milestones', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_submissions', to='institutions.studentprofile')),
            ],
            options={
                'verbose_name': 'Student Milestone Submission',
                'verbose_name_plural': 'Student Milestone Submissions',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'milestone'), name='unique_student_milestone_submission')],
            },
        ),
    ]
