# Generated by Django 6.0.8 on 2026-08-18 17:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0008_aicoachconversation_aicoachmessage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBankDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_name', models.CharField(default='Nexus Edutech Consult Ltd', max_length=255)),
                ('bank_name', models.CharField(default='Zenith Bank Plc', max_length=255)),
                ('account_number', models.CharField(default='1228490211', max_length=50)),
                ('sort_code_or_swift', models.CharField(blank=True, help_text='Optional Sort Code, SWIFT, or Branch Code', max_length=50)),
                ('currency', models.CharField(default='NGN', help_text='e.g. NGN, USD, GBP', max_length=10)),
                ('payment_instructions', models.TextField(default='Please include your Institution Name and Invoice Reference in the transfer narration/remark. Once transfer is completed, upload your payment receipt directly to the portal.', help_text='Instructions displayed on generated invoices and the payment portal')),
                ('support_email', models.EmailField(default='billing@nexus.ng', max_length=254)),
                ('support_phone', models.CharField(blank=True, default='+234 (0) 800 000 NEXUS', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='If active, this bank account will appear on newly generated invoices')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Bank Detail',
                'verbose_name_plural': 'Company Bank Details',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Unique identifier e.g. foundation, standard, flagship', max_length=50, unique=True)),
                ('name', models.CharField(help_text='e.g. Foundation Tier, Standard Tier, Flagship Enterprise', max_length=100)),
                ('target_institution_type', models.CharField(blank=True, help_text='e.g. Colleges of Education, State Universities, Federal Universities', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('base_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Annual or base license fee (in specified currency)', max_digits=12)),
                ('setup_onboarding_fee', models.DecimalField(decimal_places=2, default=150000.0, help_text='One-time onboarding & faculty calibration fee', max_digits=12)),
                ('per_student_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Per student seat fee if applicable', max_digits=10)),
                ('max_students', models.PositiveIntegerField(default=5000, help_text='Student seat capacity limit (0 for unlimited)')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of feature bullet strings')),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('billing_cycle', models.CharField(choices=[('ANNUAL', 'Annual'), ('ONE_TIME', 'One-Time Pilot'), ('SEMESTER', 'Per Semester')], default='ANNUAL', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Plan & Fee Structure',
                'verbose_name_plural': 'Pricing Plans & Fee Structures',
                'ordering': ['base_fee'],
            },
        ),
        migrations.AlterField(
            model_name='institution',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Invoice Payment'), ('PAYMENT_SUBMITTED', 'Payment Submitted (Under Review)'), ('ACTIVE', 'Active'), ('PROVISIONING', 'Provisioning'), ('SUSPENDED', 'Suspended'), ('REJECTED', 'Payment Rejected')], default='ACTIVE', max_length=20),
        ),
        migrations.CreateModel(
            name='InstitutionInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(help_text='e.g. INV-NEXUS-2026-0001', max_length=60, unique=True)),
                ('plan_name', models.CharField(max_length=100)),
                ('issued_to_name', models.CharField(help_text='Institutional Admin or Contact Name', max_length=255)),
                ('issued_to_email', models.EmailField(max_length=254)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('setup_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid / Pending Transfer'), ('PAYMENT_SUBMITTED', 'Payment Submitted (Under Review)'), ('PAID', 'Paid & Confirmed'), ('VOID', 'Void / Cancelled'), ('REJECTED', 'Payment Proof Rejected')], default='UNPAID', max_length=30)),
                ('bank_details_snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot of company bank details at the time of invoice issuance')),
                ('items_breakdown', models.JSONField(blank=True, default=list, help_text="List of line items e.g. [{'description': '...', 'amount': 1500000}]")),
                ('due_date', models.DateField()),
                ('payment_reference', models.CharField(blank=True, help_text='Bank transaction reference number entered by payer', max_length=100)),
                ('payment_receipt_file', models.FileField(blank=True, help_text='Uploaded bank transfer receipt or proof', null=True, upload_to='payment_receipts/%Y/%m/')),
                ('payer_bank_name', models.CharField(blank=True, max_length=150)),
                ('payer_account_name', models.CharField(blank=True, max_length=150)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_notes', models.TextField(blank=True, help_text='Notes/remarks from the institution regarding the transfer')),
                ('payment_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes by System Admin during verification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_invoices', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='institutions.institution')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='institutions.pricingplan')),
            ],
            options={
                'verbose_name': 'Institution Invoice',
                'verbose_name_plural': 'Institution Invoices',
                'ordering': ['-created_at'],
            },
        ),
    ]
