# Generated by Django 6.0.8 on 2026-08-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0009_companybankdetail_pricingplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutioninvoice',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='VAT Amount'),
        ),
        migrations.AddField(
            model_name='institutioninvoice',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=7.5, max_digits=5, verbose_name='VAT Rate (%)'),
        ),
    ]
