# Generated by Django 6.0.8 on 2026-08-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0011_loginotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsession',
            name='first_semester_end_date',
            field=models.DateField(blank=True, help_text='First semester end date', null=True),
        ),
        migrations.AddField(
            model_name='academicsession',
            name='first_semester_start_date',
            field=models.DateField(blank=True, help_text='First semester start date', null=True),
        ),
        migrations.AddField(
            model_name='academicsession',
            name='second_semester_end_date',
            field=models.DateField(blank=True, help_text='Second semester end date', null=True),
        ),
        migrations.AddField(
            model_name='academicsession',
            name='second_semester_start_date',
            field=models.DateField(blank=True, help_text='Second semester start date', null=True),
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='current_semester',
            field=models.CharField(choices=[('FIRST_SEMESTER', 'First Semester'), ('SECOND_SEMESTER', 'Second Semester')], default='FIRST_SEMESTER', max_length=30),
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='end_date',
            field=models.DateField(blank=True, help_text='Overall session end date', null=True),
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='start_date',
            field=models.DateField(blank=True, help_text='Overall session start date', null=True),
        ),
    ]
