# Generated by Django 6.0.8 on 2026-08-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0012_academicsession_first_semester_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicprogram',
            name='siwes_academic_impact',
            field=models.CharField(choices=[('VACATION_ONLY', 'Vacation Only (Zero Academic Semester Disruption)'), ('SECOND_SEMESTER_SUBSTITUTE', 'Replaces Second Semester Coursework'), ('FULL_SESSION_ATTACHMENT', 'Replaces Full Academic Session'), ('EXEMPT', 'No Academic Impact')], default='SECOND_SEMESTER_SUBSTITUTE', help_text='Specifies whether SIWES runs purely during vacation or substitutes regular semester coursework', max_length=35),
        ),
        migrations.AddField(
            model_name='academicprogram',
            name='siwes_pattern',
            field=models.CharField(choices=[('SPLIT_200L_300L', 'Split Vacation (3 Mo @ 200L End + 3 Mo @ 300L End)'), ('SEM2_300L', '300 Level Second Semester (6 Months Continuous)'), ('YEAR4_400L_EXTENDED', '400 Level Extended (6 to 9 Months Attachment)'), ('ND_VACATION', 'ND Industrial Attachment (3 to 4 Months Vacation)'), ('POST_ND_MANDATORY', 'Post-ND Mandatory Industrial Training (12 Months)'), ('TEACHING_PRACTICE', 'Teaching Practice / Practicum (3 to 6 Months)'), ('EXEMPT', 'Exempt / Non-Participating (0 Months)')], default='SEM2_300L', help_text='Operational timeline and calendar structure for student industrial training', max_length=35),
        ),
        migrations.AddField(
            model_name='academicprogram',
            name='siwes_target_levels',
            field=models.JSONField(blank=True, default=list, help_text='List of qualifying level numbers, e.g. [2, 3] for split vacation or [4] for 400L'),
        ),
    ]
