# Generated by Django 6.0.8 on 2026-08-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0013_academicprogram_siwes_academic_impact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicprogram',
            name='award_level',
            field=models.CharField(choices=[('BSC', 'Bachelor of Science (B.Sc.)'), ('BTECH', 'Bachelor of Technology (B.Tech.)'), ('BENG', 'Bachelor of Engineering (B.Eng.)'), ('BA', 'Bachelor of Arts (B.A.)'), ('BED', 'Bachelor of Education (B.Ed.)'), ('LLB', 'Bachelor of Laws (LL.B.)'), ('MBBS', 'Bachelor of Medicine & Surgery (MBBS)'), ('ND', 'National Diploma (ND)'), ('HND', 'Higher National Diploma (HND)'), ('NCE', 'Nigeria Certificate in Education (NCE)'), ('PGD', 'Postgraduate Diploma (PGD)'), ('MSC', 'Master of Science (M.Sc.)')], default='BSC', max_length=20),
        ),
    ]
