# Generated by Django 6.0.8 on 2026-08-16 01:36

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDivision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. School of Information and Communication Technology', max_length=200)),
                ('code', models.CharField(blank=True, help_text='e.g. SICT', max_length=20)),
                ('division_type', models.CharField(choices=[('FACULTY', 'Faculty'), ('SCHOOL', 'School'), ('COLLEGE', 'College')], default='FACULTY', max_length=20)),
                ('dean_name', models.CharField(blank=True, max_length=150)),
                ('dean_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Division (Faculty / School)',
                'verbose_name_plural': 'Academic Divisions (Faculties / Schools)',
                'ordering': ['institution', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Federal University of Technology, Minna', max_length=255, unique=True)),
                ('short_name', models.CharField(help_text='e.g. FUTMinna / YabaTech', max_length=60)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('institution_type', models.CharField(choices=[('UNIVERSITY', 'University'), ('POLYTECHNIC', 'Polytechnic'), ('COLLEGE_OF_EDUCATION', 'College of Education'), ('MONOTECHNIC', 'Monotechnic')], default='UNIVERSITY', max_length=30)),
                ('ownership', models.CharField(choices=[('FEDERAL', 'Federal Government'), ('STATE', 'State Government'), ('PRIVATE', 'Private')], default='FEDERAL', max_length=20)),
                ('regulator', models.CharField(choices=[('NUC', 'National Universities Commission (NUC)'), ('NBTE', 'National Board for Technical Education (NBTE)'), ('NCCE', 'National Commission for Colleges of Education (NCCE)')], default='NUC', max_length=20)),
                ('tier_two_term', models.CharField(choices=[('FACULTY', 'Faculty'), ('SCHOOL', 'School'), ('COLLEGE', 'College')], default='FACULTY', help_text="Customizes UI label: 'Faculty' in Universities, 'School' in Polytechnics/COEs, 'College' in Collegiate institutions", max_length=20)),
                ('domain_whitelist', models.JSONField(blank=True, default=list, help_text="Email domains allowed for institutional staff and student self-enrollment e.g. ['@futminna.edu.ng']")),
                ('address', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, help_text='Nigerian State e.g. Niger, Lagos, Kaduna', max_length=50)),
                ('is_founding_partner', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PROVISIONING', 'Provisioning'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Department of Software Engineering', max_length=200)),
                ('code', models.CharField(blank=True, help_text='e.g. SWE', max_length=20)),
                ('hod_name', models.CharField(blank=True, help_text='Head of Department Name', max_length=150)),
                ('hod_email', models.EmailField(blank=True, max_length=254)),
                ('siwes_eligible', models.BooleanField(default=True, help_text='Designates whether students in this department participate in national SIWES cycles')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='institutions.academicdivision')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='institutions.institution')),
            ],
            options={
                'verbose_name': 'Academic Department',
                'verbose_name_plural': 'Academic Departments',
                'ordering': ['division', 'name'],
                'unique_together': {('division', 'name')},
            },
        ),
        migrations.AddField(
            model_name='academicdivision',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='institutions.institution'),
        ),
        migrations.CreateModel(
            name='InstitutionalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='e.g. FUTMinna 2025/2026 SIWES Operational Guidelines', max_length=255)),
                ('doc_type', models.CharField(choices=[('STUDENT_HANDBOOK', 'Student Handbook'), ('SIWES_CALENDAR', 'SIWES / ITF Guidelines & Calendar'), ('CURRICULUM_BMAS', 'Curriculum Standards (CCMAS / BMAS)'), ('EMPLOYER_BRIEF', 'Employer Partnership Brief'), ('POLICY', 'Institutional Policy & Code of Conduct')], default='STUDENT_HANDBOOK', max_length=30)),
                ('file_path', models.CharField(blank=True, help_text='Relative storage or media path', max_length=500)),
                ('content_hash', models.CharField(blank=True, help_text='SHA-256 hash of document for auditability', max_length=64)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('embedding_status', models.CharField(choices=[('PENDING', 'Pending Ingestion'), ('INDEXED', 'Indexed in pgvector'), ('FAILED', 'Failed Processing')], default='PENDING', max_length=20)),
                ('raw_text', models.TextField(blank=True, help_text='Extracted text from document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='institutions.department')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='institutions.academicdivision')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='institutions.institution')),
            ],
            options={
                'verbose_name': 'Institutional Document',
                'verbose_name_plural': 'Institutional Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_label', models.CharField(help_text='e.g. 2025/2026', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('current_semester', models.CharField(choices=[('FIRST_SEMESTER', 'First Semester (Harmattan / Alpha)'), ('SECOND_SEMESTER', 'Second Semester (Rain / Omega)')], default='FIRST_SEMESTER', max_length=30)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='institutions.institution')),
            ],
            options={
                'verbose_name': 'Academic Session',
                'verbose_name_plural': 'Academic Sessions',
                'ordering': ['-session_label', '-is_current'],
                'unique_together': {('institution', 'session_label')},
            },
        ),
        migrations.CreateModel(
            name='AcademicProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. B.Tech Software Engineering / ND Computer Science', max_length=200)),
                ('program_code', models.CharField(blank=True, help_text='e.g. SWE-BTECH / ND-CS', max_length=30)),
                ('award_level', models.CharField(choices=[('BSC', 'Bachelor of Science (B.Sc.)'), ('BTECH', 'Bachelor of Technology (B.Tech.)'), ('BENG', 'Bachelor of Engineering (B.Eng.)'), ('BA', 'Bachelor of Arts (B.A.)'), ('LLB', 'Bachelor of Laws (LL.B.)'), ('ND', 'National Diploma (ND)'), ('HND', 'Higher National Diploma (HND)'), ('NCE', 'Nigeria Certificate in Education (NCE)'), ('PGD', 'Postgraduate Diploma (PGD)'), ('MSC', 'Master of Science (M.Sc.)')], default='BSC', max_length=20)),
                ('duration_years', models.PositiveSmallIntegerField(default=4, help_text='Standard program duration in years (e.g. 5 for Engineering, 2 for ND, 3 for NCE)')),
                ('siwes_duration_months', models.PositiveSmallIntegerField(default=6, help_text='Typical SIWES attachment period in months (0 if not applicable)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='institutions.department')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='institutions.institution')),
            ],
            options={
                'verbose_name': 'Academic Programme',
                'verbose_name_plural': 'Academic Programmes',
                'ordering': ['department', 'name'],
                'unique_together': {('department', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='academicdivision',
            unique_together={('institution', 'name')},
        ),
        migrations.CreateModel(
            name='InstitutionalDocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField()),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('section_reference', models.CharField(blank=True, help_text='e.g. Section 4.2: Placement Prerequisites', max_length=200)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, help_text='1536-dimensional vector embedding for cosine similarity search in PostgreSQL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='institutions.institutionaldocument')),
            ],
            options={
                'verbose_name': 'Document Chunk (Vector)',
                'verbose_name_plural': 'Document Chunks (Vector)',
                'ordering': ['document', 'chunk_index'],
                'unique_together': {('document', 'chunk_index')},
            },
        ),
    ]
