# Generated by Django 6.0.8 on 2026-08-16 01:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_alter_institutionaldocument_content_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('SUPERADMIN', 'Institution Superadmin'), ('DIRECTOR_CAREER_SERVICES', 'Director of Career Services'), ('DEAN', 'Dean of Faculty / School'), ('HOD', 'Head of Department (HOD)'), ('COUNSELLOR', 'Faculty Career Counsellor & Evaluator')], default='SUPERADMIN', max_length=40)),
                ('title', models.CharField(blank=True, help_text='e.g. Director of ICT / Dean of SICT / HOD Computer Science', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='institutions.department')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='institutions.academicdivision')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='institutions.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_staff_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Institution Staff',
                'verbose_name_plural': 'Institution Staff',
                'ordering': ['institution', 'role', 'user__name'],
                'unique_together': {('user', 'institution')},
            },
        ),
    ]
