# Generated by Django 6.0.8 on 2026-08-16 15:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0007_studentprofile_active_pathway_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICoachConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Career & SIWES Advisory Session', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('case_summary', models.TextField(blank=True, default='', help_text='AI-synthesized 3-bullet summary of student questions for human counsellor handoff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='institutions.studentprofile')),
            ],
            options={
                'verbose_name': 'AI Coach Conversation',
                'verbose_name_plural': 'AI Coach Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AICoachMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'Student'), ('assistant', 'AI Coach'), ('system', 'System Grounding')], max_length=20)),
                ('content', models.TextField()),
                ('citations', models.JSONField(blank=True, default=list, help_text='List of grounded institutional document references with chunk IDs')),
                ('telemetry', models.JSONField(blank=True, default=dict, help_text='Latency, tokens, model name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='institutions.aicoachconversation')),
            ],
            options={
                'verbose_name': 'AI Coach Message',
                'verbose_name_plural': 'AI Coach Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CounsellingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(choices=[('PATHWAY_ALIGNMENT', 'Career Pathway & Milestone Planning'), ('SIWES_CLEARANCE', 'SIWES Placement, Logbook & Clearance'), ('ASSESSMENT_DEBRIEF', 'Psychometric & Skills Diagnostic Debrief'), ('RESUME_CV_REVIEW', 'Resume, Portfolio & Cover Letter Review'), ('EMPLOYER_PLACEMENT', 'Graduate Job Placement & Internship Advisory'), ('ACADEMIC_STANDING', 'Academic Standing & CGPA Improvement')], max_length=40)),
                ('student_notes', models.TextField(blank=True, default='', help_text='Student description of guidance needed')),
                ('status', models.CharField(choices=[('REQUESTED', 'Session Requested'), ('CONFIRMED', 'Confirmed / Scheduled'), ('COMPLETED', 'Completed'), ('RESCHEDULED', 'Rescheduled'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=30)),
                ('preferred_date', models.DateField()),
                ('preferred_time_slot', models.CharField(help_text="e.g. '10:00 AM - 10:45 AM' or '2:00 PM - 2:45 PM'", max_length=50)),
                ('scheduled_datetime', models.DateTimeField(blank=True, null=True)),
                ('meeting_mode', models.CharField(choices=[('IN_PERSON', 'In-Person (Department Office)'), ('VIRTUAL_CALL', 'Virtual Video / Voice Call')], default='IN_PERSON', max_length=30)),
                ('meeting_location', models.CharField(blank=True, default='Departmental Career & SIWES Office', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counsellor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sessions', to='institutions.institutionstaff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselling_sessions', to='institutions.studentprofile')),
            ],
            options={
                'verbose_name': 'Counselling Session',
                'verbose_name_plural': 'Counselling Sessions',
                'ordering': ['-preferred_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CounsellingCaseNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField(help_text='Key takeaways, obstacles identified, and advice given')),
                ('action_items', models.JSONField(blank=True, default=list, help_text="List of [{task: '...', due_date: '...', done: False}]")),
                ('is_confidential', models.BooleanField(default=True, help_text='Visible only to assigned faculty counsellors and HOD')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_notes', to='institutions.institutionstaff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counsellor_case_notes', to='institutions.studentprofile')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_notes', to='institutions.counsellingsession')),
            ],
            options={
                'verbose_name': 'Counselling Case Note',
                'verbose_name_plural': 'Counselling Case Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessment_type', models.CharField(choices=[('BIG_FIVE', 'Big Five Personality Inventory (OCEAN)'), ('HOLLAND_RIASEC', 'Holland RIASEC Vocational Interests'), ('NUMERICAL_REASONING', 'Numerical & Logical Reasoning'), ('DIGITAL_SKILLS', 'Digital & Technical Skill Diagnostic')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('instructions', models.TextField(blank=True, default='')),
                ('estimated_minutes', models.PositiveIntegerField(default=10)),
                ('total_questions', models.PositiveIntegerField(default=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(blank=True, help_text='Null for national standard assessments; set for institution-customized tests.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_assessments', to='institutions.institution')),
            ],
            options={
                'verbose_name': 'Diagnostic Assessment',
                'verbose_name_plural': 'Diagnostic Assessments',
                'ordering': ['assessment_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('prompt', models.TextField(help_text='Question text or psychometric statement')),
                ('dimension', models.CharField(help_text="Subscale/Trait code (e.g. 'OPENNESS', 'CONSCIENTIOUSNESS', 'REALISTIC', 'INVESTIGATIVE', 'LOGIC')", max_length=50)),
                ('is_reverse_scored', models.BooleanField(default=False, help_text='True if Likert scale must be inverted (6 - score)')),
                ('question_type', models.CharField(choices=[('LIKERT_5', '5-Point Likert Scale (1-5)'), ('MULTIPLE_CHOICE', 'Multiple Choice Single Answer')], default='LIKERT_5', max_length=30)),
                ('options', models.JSONField(blank=True, default=list, help_text="For multiple-choice items: [{id: 'A', text: '...', is_correct: True, points: 10}]")),
                ('explanation', models.TextField(blank=True, default='')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='institutions.diagnosticassessment')),
            ],
            options={
                'verbose_name': 'Diagnostic Question',
                'verbose_name_plural': 'Diagnostic Questions',
                'ordering': ['assessment', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='StudentAssessmentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='IN_PROGRESS', max_length=30)),
                ('raw_responses', models.JSONField(default=dict, help_text='Dict of {question_id: selected_value}')),
                ('dimension_scores', models.JSONField(default=dict, help_text="Computed subscale scores: {'OPENNESS': 82.5, 'CONSCIENTIOUSNESS': 90.0, ...}")),
                ('summary_code', models.CharField(blank=True, default='', help_text="e.g. Holland 3-letter code 'IRC' or Big Five summary", max_length=20)),
                ('percentile_rank', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('summary_report', models.TextField(blank=True, default='')),
                ('career_recommendations', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='institutions.diagnosticassessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_sessions', to='institutions.studentprofile')),
            ],
            options={
                'verbose_name': 'Student Assessment Session',
                'verbose_name_plural': 'Student Assessment Sessions',
                'ordering': ['-completed_at', '-started_at'],
            },
        ),
    ]
